---
title: "Ulrik Lyngs <br> Curriculum vitae"
#date: "`r Sys.Date()`"
output:
  pagedown::html_paged:
    # change to true for a self-contained document, but it'll be a litte slower for Pandoc to render
    self_contained: false
    # CDN:
    #css: [professional_cv.css, "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap-grid.min.css", "https://use.fontawesome.com/releases/v5.7.2/css/all.css"]
    # offline:
    css: ["css/professional_cv.css", "bootstrap-4.0.0-dist/css/bootstrap-grid.min.css", "fontawesome-free-5.8.1-web/css/all.css"]
    number_sections: false
links-to-footnotes: true

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(knitr)
library(here)#

#### create publications table #####
publications <- readxl::read_xlsx(here("_cv_data", "publications.xlsx"))

#### create education table #####
cv_entries <- readxl::read_xlsx(here("_cv_data", "cv_entries.xlsx"))

```


<div class="row">
```{block type="col-6 summary", echo=TRUE}
# Personal summary {.summary}
I am a computer scientist and cognitive psychologist, researching design strategies for supporting self-control over digital device use.
My research combines qualitative and quantitative methods, including surveys, interviews, usage logging, and web scraping.

```

```{block type='col-6', echo=TRUE}
# Contact information {.box}
<div class="info-box">

| Center | Left |
|:------:|:-----|
| <i class="fas fa-map-marker-alt"></i>|Department of Computer Science,\
University of Oxford, UK|
| <i class="fas fa-envelope"></i> | ulrik.lyngs\@cs.ox.ac.uk |
| <i class="fas fa-globe"></i> | [ulriklyngs.com](https://ulriklyngs.com) |
| <i class="fab fa-github"></i> | [ulyngs](https://github.com/ulyngs) |
 
</div>

```

</div>


<div class="row pageone">

<div class='col-6 left'>

# Selected Publications {.publications}
```{r}
# create helper function for taking one name and replacing the first name with initial and dot
replace_first_name_with_initial_and_dot <- function(author_name) {
  str_replace(author_name, "(?<=\\S)\\S+", "\\.")
}

# create function for doing this for an entry of authors
replace_first_names_in_list_with_initial_and_dot <- function(authors){
  authors_split <- str_split(authors, ",") %>% 
    map(str_trim)
  
  authors_split[[1]] %>% map_chr(replace_first_name_with_initial_and_dot) %>% 
    paste0(collapse = ", ")
}

# create table
publications %>%
  filter(professional_2_page == 'y') %>%
  arrange(desc(year), type) %>%
  mutate(authors_abbrev = map_chr(authors_full, replace_first_names_in_list_with_initial_and_dot)) %>% 
  mutate(author_year = str_c(authors_abbrev, " (", year, "). ")) %>%
  mutate(title = ifelse(!is.na(url), str_c("[", title, "](", url, ")"), title)) %>%  #turn title into link
  mutate(title = str_c("<span style='text-decoration: underline'>", title, "</span>")) %>% #underline title
  mutate(prof_venue = replace_na(prof_venue, "")) %>%
  mutate(citation = ifelse(!is.na(award),
                           str_c(author_year, title, prof_venue, "<i class='fas fa-award'></i><em>", award, "</em>", sep = " "),
                           str_c(author_year, title, prof_venue, sep = " "))) %>%
  mutate(citation = str_replace(citation, "U\\. Lyngs", "**U\\. Lyngs**")) %>%  # make my name bold
  select(citation) %>%
  knitr::kable()

# publications %>%
#   filter(professional_2_page == 'y') %>% 
#   arrange(desc(year), type) %>% 
#   mutate(author_year = str_c(authors_full, " (", year, "). ")) %>% 
#   #mutate(author_year = str_c("*", authors, " (", year, ")*. ")) %>%  #italicise authors and year
#   mutate(title = ifelse(!is.na(url), str_c("[*", title, "*](", url, ")"), title)) %>%  #turn title into link
#   #mutate(title = str_c("<span style='text-decoration: underline'>", title, "</span>")) %>% #underline title
#   mutate(prof_venue = replace_na(prof_venue, "")) %>% 
#   mutate(citation = ifelse(!is.na(award), 
#                            str_c(author_year, title, prof_venue, "<i class='fas fa-award'></i><em>", award, "</em>", sep = " "),
#                            str_c(author_year, title, prof_venue, sep = " "))) %>% 
#   mutate(citation = str_replace(citation, "Ulrik Lyngs", "**Ulrik Lyngs**")) %>%  # make my name bold
#   select(citation) %>% 
#   knitr::kable()




```

</div>



<div class='col-6 right'>
# Education {.education}

```{r}
cv_entries %>% 
  filter(type == 'education') %>% 
  mutate(what = str_c(what, ", ", where)) %>% 
  mutate(year = str_c(year_begin, " --- ", year_end)) %>% 
  select(year, what) %>% 
  kable()
```

# Technical skills {.technical}
```{r}
cv_entries %>% 
  filter(type == 'technical') %>% 
  mutate(what = str_c("- *", what, "* ", additional_info)) %>% 
  select(what) %>% 
  kable()
```

# Software {.cv-table .nohead .vertical-top}
```{r}
cv_entries %>% 
  filter(type == 'programming') %>% 
  replace_na(list(where = "", additional_info = "")) %>% 
  mutate(what = str_c(what, ", ", where, "<br>", additional_info)) %>% 
  select(year_begin, what) %>% 
  arrange(desc(year_begin)) %>% 
  kable()
```

</div>

<!-- here ends the row i.e. the first page -->
</div>

<!-- <br class="pageBreak" /> -->

<!-- here starts the second page -->
<div class="row pagetwo">


<!-- here starts the first column -->
<div class="col-6 left-pagetwo">
# Selected work experience {.work}
```{r}
cv_entries %>% 
  filter(type == 'work' & professional_2_page == 'y') %>% 
  mutate(what = str_c("<span class='work-title'>", what, "</span><br class='work-break'>", where, "<br>", additional_info)) %>% 
  mutate(year = ifelse(!is.na(year_end), str_c(year_begin, " --- ", year_end), year_begin)) %>% 
  select(year, what) %>% 
  kable()
```


# Grants and Awards {.grants}
 
```{r}
cv_entries %>% 
  filter(type == 'grants_and_awards') %>%
  filter(short_cv == 'y') %>%
  mutate(where = if_else(is.na(where), "", where)) %>% 
  mutate(what = str_c(what, " (", additional_info, "), ", where)) %>% 
  select(year_begin, what) %>% 
  kable()
```

# Professional development {.prof-dev}
```{r}
cv_entries %>% 
  filter(type == 'prof-dev') %>% 
  mutate(what = str_c(what, ", ", where)) %>% 
  select(year_begin, what) %>% 
  kable()
```


</div>


<!-- here starts the right column -->
<div class="col-6 right-pagetwo">

# Media coverage {.media}
```{r}
#
cv_entries %>% 
  filter(type == 'media') %>%
  select(year_begin, what) %>% 
  kable()
```

# Selected talks {.talks}
```{r}
cv_entries %>% 
  filter(professional_2_page == 'y') %>% 
  filter(type == 'talk') %>% 
  mutate(what = str_c("*", what, "*, ", where)) %>% 
  select(year_begin, what) %>% 
  kable()
```

# Personal skills & volunteering {.personal}
```{r}
cv_entries %>%
  filter(type == 'volunteering' & professional_2_page == 'y') %>%
  mutate(what = str_c("<span class='work-title'>", what, "</span><br class='work-break'>", where)) %>%
  mutate(what = ifelse(!is.na(additional_info), str_c(what, "<br>", additional_info), what)) %>%
  mutate(year = ifelse(!is.na(year_end), str_c(year_begin, " --- ", year_end), year_begin)) %>%
  arrange(order) %>%
  select(year, what) %>%
  kable()
####

```


</div>




<!-- here ends the second page -->
</div>

<!-- <br class='pageBreak'> -->

### Links